import '@/styles/global.css';
import '@ant-design/v5-patch-for-react-19';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Provider from '@/components/Provider';
import Nav from '@/components/Nav';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <AntdRegistry>
                    <Provider>
                        <Nav />
                        <main className="pt-[100px] min-h-screen">{children}</main>
                    </Provider>
                </AntdRegistry>
            </body>
        </html>
    );
}
