
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Provider from '@/components/Provider';
import ClientLayout from '@/app/ClientLayout';
import type { Metadata } from 'next';
import '@/styles/global.css';
import '@ant-design/v5-patch-for-react-19';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html>
            <body>
                <AntdRegistry>
                    <Provider>
                        <ClientLayout>{children}</ClientLayout>
                    </Provider>
                </AntdRegistry>
            </body>
        </html>
    );
}
